### ISSUE TITLE
paper 1.18 not working

### ISSUE THREAD

**Issue by ShallowAi** [MegavexNetwork/scoreboard-library#25]
on paper 1.18, seems adventure api not compatible
```
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component io.papermc.paper.adventure.AdventureComponent.adventure$component()'
        at net.megavex.scoreboardlibrary.implementation.packetAdapter.modern.objective.PaperObjectivePacketAdapter.sendProperties(PaperObjectivePacketAdapter.java:43) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at net.megavex.scoreboardlibrary.implementation.objective.ScoreboardObjectiveImpl.sendProperties(ScoreboardObjectiveImpl.java:121) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at net.megavex.scoreboardlibrary.implementation.objective.ObjectiveManagerImpl.display(ObjectiveManagerImpl.java:203) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at net.megavex.scoreboardlibrary.implementation.player.DisplayableQueue.add(DisplayableQueue.java:38) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at net.megavex.scoreboardlibrary.implementation.objective.ObjectiveManagerImpl.tick(ObjectiveManagerImpl.java:147) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at net.megavex.scoreboardlibrary.implementation.objective.ObjectiveUpdaterTask.run(ObjectiveUpdaterTask.java:36) ~[StrikeAddon-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-"f949b6d"]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-"f949b6d"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-"f949b6d"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by vytskalt** [comment]
Fixed in version 2.1.3. Thanks for reporting
