### ISSUE TITLE
Scoreboard not appearing + Packet adaper not available

### ISSUE THREAD

**Issue by therealscaled130** [MegavexNetwork/scoreboard-library#55]
For some reason, the plugin is always throwing the `NoPacketAdapterAvailableException `when trying to start it up, even though my build.gradle file looks like this: 

    dependencies {

        implementation "net.megavex:scoreboard-library-api:2.1.11"

        implementation "net.megavex:scoreboard-library-implementation:2.1.11"

        runtimeOnly "net.megavex:scoreboard-library-modern:2.1.11"
    }

with the shadowJar config looking like this:

    tasks.shadowJar {
        dependencies {
            include dependency("net.megavex:scoreboard-library-implementation:2.1.11")
            include dependency("net.megavex:scoreboard-library-api:2.1.11")
        }

        relocate("net.megavex.scoreboardlibrary", "com.example.testplugin.sb")
    }

And if I try adding the `net.megavex:scoreboard-library-modern:2.1.11` to the shadowJar config, it throws me a runtime error:
    `    java.lang.RuntimeException: failed to load scoreboard-library implementation
    	    at com.example.testplugin.sb.api.ScoreboardLibrary.loadScoreboardLibrary(ScoreboardLibrary.java:49) ~ 
    [_papermake_hooked_A7V47SFiZQTiAfUTWzSZCuzo6SMXYTfR.jar:?]
    	    at com.example.testplugin.TestPlugin.onEnable(TestPlugin.java:73) ~ 
   [_papermake_hooked_A7V47SFiZQTiAfUTWzSZCuzo6SMXYTfR.jar:?]
    	    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    	    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~ 
  [paper-1.20.4.jar:git-Paper-497]
    	    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper- 
   1.20.4.jar:git-Paper-497]
   	    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1- 
   SNAPSHOT.jar:?]
   	    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
   	    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
   	    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
    	    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
    	    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
    	    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
    	    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
   	    at java.lang.Thread.run(Thread.java:842) ~[?:?]
        Caused by: java.lang.reflect.InvocationTargetException
    	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
    	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
    	    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
    	    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
    	    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
    	    at com.example.testplugin.sb.api.ScoreboardLibrary.loadScoreboardLibrary(ScoreboardLibrary.java:40) ~	... 13 more
        Caused by: java.lang.NoClassDefFoundError: com.example.testplugin/sb/implementation/packetAdapter/PacketAdapterProvider
    	    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
    	    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
`

Also if I try creating a scoreboard for all players, it doesn't show up, I suppose because of the `NoPacketAdapterAvailableException`

**Comment by vytskalt** [comment]
In your shadowjar config try including the library like this:

include dependency("net.megavex:scoreboard-library-*")

**Comment by therealscaled130** [comment]
lemme try that rq

**Comment by therealscaled130** [comment]
Hmm... for some reason it's now not shading it in at all...

**Comment by vytskalt** [comment]
what about `include dependency("net.megavex:scoreboard-library-.*:.*")` ?

**Comment by vytskalt** [comment]
closing for now. if you're still having issues let me know

**Comment by therealscaled130** [comment]
Yes, works now. Thanks
